version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbdotnet
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306" # Expose le port 3306
    volumes:
      - mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
volumes:
  mysqldata:
